### PR TITLE
Fix panic when bindings reference a deleted cluster

### LINKED ISSUE #95: Deleting a binding on a non-existing RabbitMQ Cluster causes a panic
## Describe the bug
When a Binding object is marked for deletion and RabbitMQ Cluster does not exist, the operator panics.

## To Reproduce
Steps to reproduce the behavior: **Untested**
1. Create a RabbitMQ cluster and a valid binding
2. Delete RabbitMQ cluster
3. Delete the binding

Include any YAML or manifest necessary to reproduce the problem.

**Expected behavior**
The Operator deletes the binding object and/or removes the finalizer in the Binding object.

## Screenshots
Log snippet
```
2021-04-06T09:07:59.848Z        INFO    controller-runtime.manager.controller.binding   Deleting        {"reconciler group": "rabbitmq.com", "reconciler kind": "Binding", "name": "x-invoices-to-invoices", "namespace": "rabbitmq-red"}
E0406 09:07:59.849198       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 374 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1581480, 0x22be540)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1581480, 0x22be540)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/michaelklishin/rabbit-hole/v2.newRequestWithBody(0x0, 0x171d9c8, 0x6, 0xc00099e990, 0x26, 0x0, 0x0, 0x0, 0x7f9f229665a0, 0xc0005e9728, ...)
        /go/pkg/mod/github.com/michaelklishin/rabbit-hole/v2@v2.6.0/client.go:100 +0x37
github.com/michaelklishin/rabbit-hole/v2.(*Client).DeleteBinding(0x0, 0x22808b8, 0x1, 0xc000047d30, 0xa, 0x22808b8, 0x1, 0xc000047d20, 0x8, 0xc000047d28, ...)
        /go/pkg/mod/github.com/michaelklishin/rabbit-hole/v2@v2.6.0/bindings.go:217 +0x330
github.com/rabbitmq/messaging-topology-operator/controllers.(*BindingReconciler).deleteBinding(0xc000422900, 0x197ab58, 0xc00077d590, 0x0, 0xc000754d00, 0x0, 0xc000047cd0)
        /workspace/controllers/binding_controller.go:156 +0x17b
github.com/rabbitmq/messaging-topology-operator/controllers.(*BindingReconciler).Reconcile(0xc000422900, 0x197ab58, 0xc00077d590, 0xc000047cd0, 0xc, 0xc000403170, 0x16, 0xc00077d590, 0xc000030000, 0x15feb80, ...)
        /workspace/controllers/binding_controller.go:67 +0xcfe
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002e8140, 0x197aab0, 0xc000326000, 0x15cb320, 0xc000774a80)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x30d
```
 
## Additional context
The problem seems to be in `Reconcile()` function, which does not cover the case of a binding marked for deletion *and* RabbitMQ Cluster object does not exist. 

https://github.com/rabbitmq/messaging-topology-operator/blob/02fc8f06eca426faaa4a8009568ef397fa780d1f/controllers/binding_controller.go#L59-L65

We have done a quick spike to verify this, but we should fix this properly and add a test using the framework in #89.

### PR DESCRIPTION
**Pull request by coro**
This closes #95 

**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed
**Note to contributors:** remember to re-generate client set if there are any API changes

## Summary Of Changes

This change prevents the controller from panicking when trying to reconcile bindings that reference a non-existent RabbitmqCluster.

## Additional Context

This also adds integration tests to the binding controller.

### CODE REVIEW

**Review by MirahImage — APPROVED** [review]

**Review by MirahImage — APPROVED** [review]

File: controllers/binding_controller_test.go [hunk 1]
```diff
@@ -0,0 +1,217 @@
...
+				Expect(client.Delete(ctx, &binding)).To(Succeed())
+				Consistently(func() bool {
+					err := client.Get(ctx, types.NamespacedName{Name: binding.Name, Namespace: binding.Namespace}, &topology.Binding{})
+					return apierrors.IsNotFound(err)
+				}, 5).Should(BeFalse())
+				Expect(observedEvents()).To(ContainElement("Warning FailedDelete failed to delete binding"))
+			})
+		})
+
+		When("the RabbitMQ Client fails to generate", func() {
```
Comment (Zerpet) [inline controllers/binding_controller_test.go:178]: I had to read the function `prepareNoSuchClusterError()` to understand the intention behind "when the RabbitMQ Client fails to generate". Perhaps we can improve the wording of this `when`?
Perhaps be super specific, like "when the RabbitMQ cluster is nil"?

**Review by Zerpet — APPROVED** [review]
Looks good to me. Left a cosmetic comment, feel free to merge without addressing it 🙂

**Comment by ChunyiLyu** [comment]
Looks good! Just need to remember to squash merge :)
